language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0

before_install:
  - "gem install bundler"

script: "bundle exec rake"

gemfile:
  - "gemfiles/simple_form_3_0.gemfile"
  - "gemfiles/simple_form_3_1.gemfile"
